version: "3"

services:
  api:
    image: "node:11"
    user: "node"
    working_dir: /home/node/app
    container_name: node
    ports:
      - "9090:8081"
    volumes:
      - .:/home/node/app
    networks:
      - net
    depends_on:
      - db
    environment:
      - NODE_ENV=devlopment
      - PORT=8081
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=18563026
      - EGG_SERVER=local
      - NODE_ENV=development
    expose:
        - "8081"
    command: "npm start"
  db:
    image: mysql:5.7
    volumes:
      - db-storage:/var/lib/mysql/data
    container_name: mysql
    command: /bin/bash
    ports:
      - "3316:3316"
    networks:
      - net
volumes:
  db-storage:
networks:
  net:
#Optionals
# networks:
